<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="13.2.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>72b6cab8-33b1-4f13-8a87-267e2987c691</UserSecretsId> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" Version="13.2.0" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="13.2.0" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.2.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.0.2" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthServer\AuthServer.csproj" />
    <ProjectReference Include="..\CustomersTask4\CustomersTask4.csproj" />
  </ItemGroup>

</Project>
