services:
  customerstask4:
    image: ${DOCKER_REGISTRY-}customerstask4
    build:
      context: .
      dockerfile: CustomersTask4/Dockerfile
    container_name: customerstask4-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=CustomersManagmentDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=true;Encrypt=false;Connection Timeout=30
      - ConnectionStrings__key=this is my secret key abdo saad key
      - MongoDbSetting__ConnectionString=mongodb://admin:Password123!@mongo:27017
      - MongoDbSetting__DatabaseName=CustomersManagment
      - DatabaseProvidor=sql
    ports:
      - "8080:80"
    depends_on:
      - mongo
    networks:
      - customersnetwork
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: customerstask4-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password123!
      - MONGO_INITDB_DATABASE=CustomersDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - customersnetwork
    restart: unless-stopped

volumes:
  mongodb_data:
  mongodb_config:

networks:
  customersnetwork:
    driver: bridge